package ruleengine

// DefaultRules returns a curated set of AIOps rules covering the most
// common production-operations scenarios: system metrics, network,
// database, application, and security. Each rule carries patterns that
// trigger on incident descriptions, alert names, or log fragments
// commonly seen in ongrid's knowledge base and agent workflows.
func DefaultRules() []Rule {
	return []Rule{
		// ----- system -----
		{
			ID:          "sys-cpu-high",
			Title:       "CPU High Load",
			Description: "CPU usage exceeds 90% sustained; investigate runaway processes or insufficient capacity.",
			Category:    "system",
			Tags:        []string{"cpu", "performance", "load"},
			Patterns:    []string{"cpu", "high load", "load average", "re:cpu.*(?:usage|util).*[89]\\d%", "steal"},
			Priority:    90,
			Response:    "1) Run `top -b -n 1` to identify top consumers. 2) Check for runaway jobs with `ps aux --sort=-%cpu`. 3) If steal time is high, suspect noisy-neighbor on the hypervisor. 4) Consider scaling up or distributing workload.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "sys-disk-full",
			Title:       "Disk Space Exhaustion",
			Description: "Disk usage above threshold; risk of write failures and service outages.",
			Category:    "system",
			Tags:        []string{"disk", "storage", "space"},
			Patterns:    []string{"disk full", "disk space", "no space left", "re:disk.*(?:usage|util).*9[0-9]%", "inode"},
			Priority:    95,
			Response:    "1) Run `df -h` and `df -i` to identify full partitions. 2) Clear old logs: `journalctl --vacuum-size=500M`. 3) Find large files: `du -sh /* | sort -rh | head`. 4) Expand volume or move data if needed.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "sys-memory-leak",
			Title:       "Memory Leak / OOM",
			Description: "Process memory growing unbounded or OOM-killer triggered.",
			Category:    "system",
			Tags:        []string{"memory", "oom", "leak"},
			Patterns:    []string{"memory leak", "oom", "out of memory", "re:memory.*(?:usage|util).*9[0-9]%", "kill process"},
			Priority:    90,
			Response:    "1) Check dmesg for OOM-killer logs. 2) Review `/proc/<pid>/status` for RSS growth. 3) Use `valgrind` or `pprof` for leak analysis. 4) Set cgroup memory limits as a safety net.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "sys-swap-thrashing",
			Title:       "Swap Thrashing",
			Description: "Excessive swap usage causing severe performance degradation.",
			Category:    "system",
			Tags:        []string{"swap", "memory", "performance"},
			Patterns:    []string{"swap", "thrashing", "si so", "re:swap.*(?:used|usage).*[5-9]\\d%"},
			Priority:    80,
			Response:    "1) Check `vmstat 1` for high si/so columns. 2) Identify memory-hungry processes. 3) Add physical RAM or tune vm.swappiness. 4) Consider disabling swap for latency-sensitive workloads.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		// ----- network -----
		{
			ID:          "net-unreachable",
			Title:       "Network Unreachable",
			Description: "Host or service cannot be reached over the network.",
			Category:    "network",
			Tags:        []string{"network", "connectivity", "unreachable"},
			Patterns:    []string{"network unreachable", "connection refused", "no route to host", "timeout", "re:connect(?:ion)?\\s+(?:refused|timed?\\s*out)"},
			Priority:    85,
			Response:    "1) Verify physical link: `ip link show`. 2) Check routing: `ip route get <dest>`. 3) Test DNS: `dig <host>`. 4) Inspect firewall rules: `iptables -L -n`. 5) Check upstream load balancer health.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "net-packet-loss",
			Title:       "Packet Loss / NIC Errors",
			Description: "Network interface showing dropped packets or CRC errors.",
			Category:    "network",
			Tags:        []string{"network", "packet-loss", "nic"},
			Patterns:    []string{"packet loss", "dropped packets", "nic error", "re:RX_errors|TX_errors|dropped", "retransmit"},
			Priority:    80,
			Response:    "1) Check `ip -s link` for error counters. 2) Inspect `ethtool -S <iface>`. 3) Verify MTU consistency across the path. 4) Check cable / SFP hardware. 5) Run `mtr` to locate loss hop.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "net-dns-failure",
			Title:       "DNS Resolution Failure",
			Description: "DNS queries failing or returning unexpected results.",
			Category:    "network",
			Tags:        []string{"dns", "network", "resolution"},
			Patterns:    []string{"dns", "name resolution", "NXDOMAIN", "SERVFAIL", "re:dns.*(?:fail|error|timeout)"},
			Priority:    80,
			Response:    "1) Test with `dig @<server> <domain>`. 2) Check /etc/resolv.conf. 3) Verify upstream DNS server health. 4) Look for stale negative cache entries. 5) Restart systemd-resolved if applicable.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "net-port-exhaustion",
			Title:       "Ephemeral Port Exhaustion",
			Description: "Outbound connections exhausting the ephemeral port range.",
			Category:    "network",
			Tags:        []string{"network", "ports", "connection"},
			Patterns:    []string{"ephemeral port", "port exhaustion", "address already in use", "re:cannot assign.*address", "TIME_WAIT"},
			Priority:    75,
			Response:    "1) Check `ss -s` for socket summary. 2) Expand range: `sysctl net.ipv4.ip_local_port_range`. 3) Enable `tcp_tw_reuse`. 4) Investigate connection leaks in application code.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		// ----- database -----
		{
			ID:          "db-slow-queries",
			Title:       "Slow Database Queries",
			Description: "Queries exceeding latency thresholds; potential missing indexes or lock contention.",
			Category:    "database",
			Tags:        []string{"database", "slow-query", "performance"},
			Patterns:    []string{"slow query", "slow sql", "long running query", "re:query.*(?:latency|time).*[3-9]\\d{3}ms", "table lock"},
			Priority:    85,
			Response:    "1) Enable slow query log: `SET GLOBAL slow_query_log = ON`. 2) Run `EXPLAIN` on flagged queries. 3) Check for missing indexes. 4) Review lock waits: `SHOW ENGINE INNODB STATUS`. 5) Consider read replicas for read-heavy workloads.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "db-replication-lag",
			Title:       "Database Replication Lag",
			Description: "Replica falling behind primary; stale reads possible.",
			Category:    "database",
			Tags:        []string{"database", "replication", "lag"},
			Patterns:    []string{"replication lag", "replica behind", "re:Seconds_Behind_Master", "re:replication.*(?:delay|lag|behind)", "binlog"},
			Priority:    80,
			Response:    "1) Check `SHOW SLAVE STATUS` / `SHOW REPLICA STATUS`. 2) Verify network between primary and replica. 3) Look for long-running transactions on the replica. 4) Consider parallel replication.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "db-connection-pool",
			Title:       "Connection Pool Exhaustion",
			Description: "Database connection pool saturated; new requests queuing or failing.",
			Category:    "database",
			Tags:        []string{"database", "connection-pool", "exhaustion"},
			Patterns:    []string{"connection pool", "too many connections", "connection refused", "re:max_connections|pool.*(?:full|exhausted)"},
			Priority:    85,
			Response:    "1) Check current connections: `SHOW PROCESSLIST`. 2) Increase max_connections if headroom allows. 3) Review application pool settings (max_idle, max_open). 4) Identify connection leaks (unclosed connections). 5) Consider PgBouncer / ProxySQL.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		// ----- application -----
		{
			ID:          "app-service-down",
			Title:       "Service Down / Unavailable",
			Description: "A critical service is not responding to health checks.",
			Category:    "application",
			Tags:        []string{"service", "down", "health-check"},
			Patterns:    []string{"service down", "service unavailable", "health check fail", "503", "re:(?:service|process).*(?:down|crash|stop)", "SIGTERM"},
			Priority:    95,
			Response:    "1) Check process status: `systemctl status <service>`. 2) Review recent logs: `journalctl -u <service> --since '5 min ago'`. 3) Verify dependent services (DB, cache, queue). 4) Restart if safe. 5) Check resource limits (OOM, FD).",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "app-error-rate",
			Title:       "High 5xx Error Rate",
			Description: "Elevated HTTP 5xx error rate indicating server-side failures.",
			Category:    "application",
			Tags:        []string{"http", "5xx", "error-rate"},
			Patterns:    []string{"5xx", "500 error", "internal server error", "re:5[0-9]{2}.*(?:rate|count).*(?:high|elevated|spike)", "stack trace"},
			Priority:    90,
			Response:    "1) Check application logs for stack traces. 2) Verify upstream dependencies. 3) Review recent deployments for regressions. 4) Enable verbose error logging temporarily. 5) Rollback if deployment-related.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "app-latency",
			Title:       "High Latency / p99 Spike",
			Description: "Request latency significantly elevated; user experience degraded.",
			Category:    "application",
			Tags:        []string{"latency", "performance", "p99"},
			Patterns:    []string{"high latency", "latency spike", "p99", "p95", "re:latency.*(?:spike|elevated|high)", "slow response"},
			Priority:    80,
			Response:    "1) Profile application with pprof. 2) Check downstream latency (DB, cache, external API). 3) Review GC pause times. 4) Look for resource contention (CPU, disk I/O). 5) Check connection pool utilization.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "app-pod-crashloop",
			Title:       "CrashLoopBackOff / Pod Restart Loop",
			Description: "Kubernetes pod stuck in restart loop due to repeated crashes.",
			Category:    "application",
			Tags:        []string{"kubernetes", "pod", "crashloop", "restart"},
			Patterns:    []string{"CrashLoopBackOff", "pod restart", "re:restart.*count.*[5-9]\\d*", "pod evicted", "OOMKilled"},
			Priority:    90,
			Response:    "1) Describe pod: `kubectl describe pod <name>`. 2) Check container logs: `kubectl logs <pod> --previous`. 3) Verify resource limits. 4) Check liveness/readiness probe config. 5) Review init container dependencies.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		// ----- security -----
		{
			ID:          "sec-ssh-brute",
			Title:       "SSH Brute Force Attack",
			Description: "Repeated failed SSH login attempts detected.",
			Category:    "security",
			Tags:        []string{"ssh", "brute-force", "security"},
			Patterns:    []string{"ssh brute", "failed login", "authentication failure", "re:ssh.*(?:fail|invalid|refused).*\\d+", "invalid user"},
			Priority:    95,
			Response:    "1) Check /var/log/auth.log for source IPs. 2) Install and configure fail2ban. 3) Restrict SSH to key-based auth only. 4) Consider IP allowlisting. 5) Change default SSH port.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "sec-tls-handshake",
			Title:       "TLS Handshake Failure",
			Description: "Clients failing TLS negotiation; certificate or cipher issues.",
			Category:    "security",
			Tags:        []string{"tls", "ssl", "certificate", "security"},
			Patterns:    []string{"tls handshake", "ssl error", "certificate expired", "certificate invalid", "re:tls.*(?:fail|error|handshake)", "cipher mismatch"},
			Priority:    80,
			Response:    "1) Check certificate validity: `openssl s_client -connect <host>:443`. 2) Verify cert chain completeness. 3) Review TLS version / cipher suite compatibility. 4) Check system clock (cert validation depends on time). 5) Renew expired certs.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
		{
			ID:          "sec-selinux-denial",
			Title:       "SELinux / AppArmor Denials",
			Description: "Security module blocking legitimate application operations.",
			Category:    "security",
			Tags:        []string{"selinux", "apparmor", "security", "denial"},
			Patterns:    []string{"selinux", "apparmor", "avc denied", "re:(?:selinux|apparmor).*(?:denied|blocked|denial)", "permission denied"},
			Priority:    75,
			Response:    "1) Check audit log: `ausearch -m AVC`. 2) Generate policy: `audit2allow -M mymodule`. 3) Review current context: `ls -Z`. 4) For AppArmor: check `aa-status`. 5) Fix with proper labels before disabling enforcement.",
			Conditions:  map[string]string{},
			Enabled:     true,
		},
	}
}
